version: '2'

networks:
  bamboo_net:
    driver: bridge

services:
  base-image:
    build: ./bamboo-base
    image: bamboo-base

  nexus:
    build: ./nexus
    restart: always
    ports:
        - 18081:8081
    networks:
        - bamboo_net

  bamboo-server:
    build: ./bamboo-server
    restart: always
    ports:
        - 8085:8085
        - 54663:54663
    links:
        - mysqldb
    volumes:
        - bamboo-home:/home/bamboo
    environment:
        BAMBOO_VERSION: 5.15.4
        BAMBOO_HOME: /home/bamboo
        BAMBOO_BAMBOO_SERVER_ID: bamboo-server
    networks:
        - bamboo_net
    depends_on:
        - base-image
        - mysqldb

  mysqldb:
     image: mysql:5.7
     volumes:
        - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: bamboo
       MYSQL_USER: bamboo
       MYSQL_PASSWORD: 5ivel!fe
     networks:
        - bamboo_net

  bamboo-agent:
     build: ./bamboo-agent
     links:
          - bamboo-server
     networks:
          - bamboo_net
     environment:
          BAMBOO_VERSION: 5.15.4
          AGENT_VERSION: 5.15.4
          BAMBOO_SERVER: bamboo-server
          BAMBOO_SERVER_PORT: 8085
          PACKAGES: "mc htop"
     depends_on:
          - base-image
          - bamboo-server
volumes:
    db_data:
    bamboo-home: