version: '2'

networks:
  bamboo_net:
    driver: bridge

services:
  nexus:
    build: ./docker-nexus
    ports:
        - 18081:8081
    networks:
        - bamboo_net

  bamboo-server:
      build: ./bamboo-server
    ports:
        - 8085:8085
        - 54663:54663
    links:
        - mysqldb
    volumes:
        - bamboo-home:/${BAMBOO_HOME}
    environment:
        BAMBOO_VERSION: ${BAMBOO_VERSION}
        BAMBOO_HOME: /home/bamboo
        BAMBOO_BAMBOO_SERVER_ID: bamboo-server
    networks:
        - bamboo_net

  mysqldb:
     image: mysql:5.7
     volumes:
        - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: bamboo
       MYSQL_USER: bamboo
       MYSQL_PASSWORD: 5ivel!fe

  bamboo-agent:
      build: ./bamboo-agent
      links:
          - bamboo-server
      networks:
          - bamboo_ne
      environment:
          BAMBOO_VERSION: ${BAMBOO_VERSION}
          BAMBOO_SERVER: bamboo-server
          BAMBOO_SERVER_PORT: 8085
          PACKAGES: "mc htop"
volumes:
    db_data:
    bamboo-home: